### PR TITLE
Add yaml for Kube Deployment

### PR DESCRIPTION
**Pull request by ajbozarth**
Part of https://github.ibm.com/CODAIT/Usability-Enhancement/issues/2

### CODE REVIEW

**Review by ptitzler — APPROVED** [review]
Deploys to Kubernetes on IBM Cloud but requires worker(s) with at least 8GB of RAM

**Comment by ajbozarth** [comment]
tested locally, deploys fine but hits the following error when running (even with 8gb)

```
[2018-07-28 03:07:36,563] ERROR in app: Exception on /model/predict [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/workspace/api/model.py", line 58, in post
    preds = self.model_wrapper.predict(text)
  File "/workspace/core/tensorflow.py", line 29, in predict
    txt_file = open("out.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'out.txt'
```

**Comment by ajbozarth** [comment]
Did some follow up testing and the above error is the standard error for when the model runs out of memory. Though the fact this could happen is documented in the README, this error is not. I'll open an issue to look into adding the exact error to a troubleshooting section.

**Comment by ajbozarth** [comment]
opened #7 for the error troubleshooting

**Comment by ajbozarth** [comment]
to test this on a kube cluster, run the following:
```
kubectl apply -f https://github.com/IBM/MAX-News-Text-Generator/raw/14c3b413c1c3aa84040720455f7fe854d44e681b/max-news-text-generator.yaml
```
then use `kubectl get all` to find the NodePort and try hitting the endpoint once it finishing deploying, which takes a really long time

**Comment by ajbozarth** [comment]
FYI this works locally with the necessary memory

**Comment by ptitzler** [comment]
Tested with 16GB RAM cloud deployment.

**Pull request merged**
